clearvars;clc;
DATA = {...
    'Lick' , '20180807_B2';...
    'Aston', '20181004_B1'};

%% Collect EPHYS ==========================================================
fprintf('Collecting ephys retinotopic maps...\n');

%% data location ==========================================================
base_path = pwd;
if ismac % laptop & portable HDD
    data_path = '/Volumes/MRI_2/PRF_EPHYS';
    home_path = '/Users/chris';
else %
    data_path = '/media/NETDISKS/VS02/VandC/PRF_EPHYS';
    home_path = '/home/chris';
end
data_fld = fullfile(data_path,'Data_proc');
start_fld=pwd;

%% get the data and info ==================================================
for m = 1:size(DATA,1)
    subj=DATA{m,1};
    sess=DATA{m,2};
    RetMap(m).Subj = subj; %#ok<*SAGROW>
    RetMap(m).Sess = sess;
    
    fprintf(['Processing ' subj ' ' sess '...\n']);
    
    %% MUA --
    cd(fullfile(data_fld,subj,sess,'MUA','PosNegBetas_4'));
    load([subj '_' sess '_allinst_PRFMUA'])
    RetMap(m).ChanMap = C;
    RetMap(m).MUA = PRF_mua;
    
    %% put it in a table
    A=[];
    for a = 1:8
        fprintf(['MUA instance ' num2str(a) '\n']);
        [TH,R]=cart2pol(PRF_mua(a).rmx(1:128,1),PRF_mua(a).rmy(1:128,1));
        A = [A; ...
            ones(128,1)*a ...
            (1:128)' ...
            C.arrayNums(:,a) ...
            C.channelNums(:,a) ...
            C.areas(:,a) ...
            PRF_mua(a).rmx(1:128,1) ...
            PRF_mua(a).rmy(1:128,1) ...
            rad2deg(TH) ...
            R ...
            PRF_mua(a).rsd(1:128,1) ...
            PRF_mua(a).rcrf(1,1:128)'...
            PRF_mua(a).rsd_fwhm(1:128,1) ...
            PRF_mua(a).beta(1,1:128)'...
            
            ]; %#ok<*AGROW>
    end
    
    RetMap(m).table_mua = array2table(A,...
        'VariableNames',{...
        'Instance',...
        'ChanIndex',...
        'Array',...
        'Chan',...
        'Area',...
        'prf_x',...
        'prf_y',...
        'prf_pol' ...
        'prf_ecc'...
        'prf_sd',...
        'prf_r2'...
        'prf_fwhm'...
        'prf_beta'...
        });
    
    %% LFP --
    cd(fullfile(data_fld,subj,sess,'LFP','PosNegBetas_4'));
    load([subj '_' sess '_allinst_PRFLFP'])
    RetMap(m).LFP = PRF_lfp;
    
    %% put it in a table
    A=[];
    for a = 1:8
        fprintf(['LFP instance ' num2str(a) '\n']);
        for f=1:5
            [TH2{f},R2{f}]=cart2pol(PRF_lfp(a,f).rmx(1:128,1),PRF_lfp(a,f).rmy(1:128,1));
        end
        
        A = [A; ...
            ones(128,1)*a ...
            (1:128)' ...
            C.arrayNums(:,a) ...
            C.channelNums(:,a) ...
            C.areas(:,a) ...
            PRF_lfp(a,1).rmx(1:128,1) ...
            PRF_lfp(a,1).rmy(1:128,1) ...
            rad2deg(TH2{1}) ...
            R2{1} ...
            PRF_lfp(a,1).rsd(1:128,1) ...
            PRF_lfp(a,1).rcrf(1,1:128)'...
            PRF_lfp(a,1).rsd_fwhm(1:128,1) ...
            PRF_lfp(a,1).beta(1,1:128)' ...
            PRF_lfp(a,2).rmx(1:128,1) ...
            PRF_lfp(a,2).rmy(1:128,1) ...
            rad2deg(TH2{2}) ...
            R2{2} ...
            PRF_lfp(a,2).rsd(1:128,1) ...
            PRF_lfp(a,2).rcrf(1,1:128)'...
            PRF_lfp(a,2).rsd_fwhm(1:128,1) ...
            PRF_lfp(a,2).beta(1,1:128)' ...
            PRF_lfp(a,3).rmx(1:128,1) ...
            PRF_lfp(a,3).rmy(1:128,1) ...
            rad2deg(TH2{3}) ...
            R2{3} ...
            PRF_lfp(a,3).rsd(1:128,1) ...
            PRF_lfp(a,3).rcrf(1,1:128)'...
            PRF_lfp(a,3).rsd_fwhm(1:128,1) ...
            PRF_lfp(a,3).beta(1,1:128)' ...
            PRF_lfp(a,4).rmx(1:128,1) ...
            PRF_lfp(a,4).rmy(1:128,1) ...
            rad2deg(TH2{4}) ...
            R2{4} ...
            PRF_lfp(a,4).rsd(1:128,1) ...
            PRF_lfp(a,4).rcrf(1,1:128)'...
            PRF_lfp(a,4).rsd_fwhm(1:128,1) ...
            PRF_lfp(a,4).beta(1,1:128)' ...
            PRF_lfp(a,5).rmx(1:128,1) ...
            PRF_lfp(a,5).rmy(1:128,1) ...
            rad2deg(TH2{5}) ...
            R2{5} ...
            PRF_lfp(a,5).rsd(1:128,1) ...
            PRF_lfp(a,5).rcrf(1,1:128)'...
            PRF_lfp(a,5).rsd_fwhm(1:128,1) ...
            PRF_lfp(a,5).beta(1,1:128)' ...
            ];
    end
    
    RetMap(m).table_lfp = array2table(A,...
        'VariableNames',{...
        'Instance',...
        'ChanIndex',...
        'Array',...
        'Chan',...
        'Area',...
        'theta_prf_x',...
        'theta_prf_y',...
        'theta_prf_sd',...
        'theta_prf_pol',...
        'theta_prf_ecc',...
        'theta_prf_r2',...
        'theta_prf_fwhm',...
        'theta_prf_beta',...
        'alpha_prf_x',...
        'alpha_prf_y',...
        'alpha_prf_pol',...
        'alpha_prf_ecc',...
        'alpha_prf_sd',...
        'alpha_prf_r2',...
        'alpha_prf_fwhm',...
        'alpha_prf_beta',...
        'beta_prf_x',...
        'beta_prf_y',...
        'beta_prf_pol',...
        'beta_prf_ecc',...
        'beta_prf_sd',...
        'beta_prf_r2',...
        'beta_prf_fwhm',...
        'beta_prf_beta',...
        'lowgamma_prf_x',...
        'lowgamma_prf_y',...
        'lowgamma_prf_pol',...
        'lowgamma_prf_ecc',...
        'lowgamma_prf_sd',...
        'lowgamma_prf_r2',...
        'lowgamma_prf_fwhm',...
        'lowgamma_prf_beta',...
        'highgamma_prf_x',...
        'highgamma_prf_y',...
        'highgamma_prf_pol',...
        'highgamma_prf_ecc',...
        'highgamma_prf_sd',...
        'highgamma_prf_r2'...
        'highgamma_prf_fwhm'...
        'highgamma_prf_beta'...
        });
    
end

%% Save together
cd(start_fld)
save('pRF_estimates_ephys','RetMap','-v7.3')
%%


%% Add the fMRI-retmaps ===================================================
RM_ephys = RetMap;

%% data location ==========================================================
base_path = pwd;
if ismac % laptop & portable HDD
    data_path = '/Volumes/MRI_2/PRF_MRI';
    home_path = '/Users/chris';
else %
    data_path = '/media/NETDISKS/VCNIN/PRF_EPHYS';
    home_path = '/home/chris';
end
data_fld = fullfile(data_path,'Data_proc');
start_fld=pwd;
