Ms={'danny','eddy'};
Ss={%'csshrf_cv0_dhrf',...
    'csshrf_cv0_mhrf',...
    %'doghrf_cv0_dhrf','doghrf_cv0_mhrf',...
    %'linhrf_cv0_dhrf','linhrf_cv0_mhrf',...
    %'linhrf_cv0_mhrf_neggain','linhrf_cv0_dhrf_neggain'...
    };

for m=1:length(Ms)
    fprintf(['MONKEY: ' Ms{m} '\n']);
    for s=1:length(Ss)
        %RF_Combine_SliceChunks_cv(Ms{m},Ss{s});
        pRF_Combine_SliceChunks_cv0(Ms{m},Ss{s});
    end
end