% ck_CollectRetmaps_fMRI

%% Add nifti reading toolbox
tool_basepath = '~/Dropbox/MATLAB_NONGIT/TOOLBOX';
addpath(genpath(fullfile(tool_basepath, 'NIfTI')));

%% Load fMRI files
MRI_path = '/Users/chris/Dropbox/CURRENT_PROJECTS/PRF/fMRI_ePhys/Data/fmri';

Monkey={'Danny','Eddy'};
for m=1:2
    MRI(m).Subj = Monkey{m};
    MRI(m).prf_pol = load_nii(...
        fullfile(MRI_path,Monkey{m},'NonReg','BestVoxEstimate',...
        'ANG.nii'));
    MRI(m).prf_ecc = load_nii(...
        fullfile(MRI_path,Monkey{m},'NonReg','BestVoxEstimate',...
        'ECC.nii'));
    MRI(m).prf_R2 = load_nii(...
        fullfile(MRI_path,Monkey{m},'NonReg','BestVoxEstimate',...
        'R2.nii'));
    MRI(m).prf_sz = load_nii(...
        fullfile(MRI_path,Monkey{m},'NonReg','BestVoxEstimate',...
        'RFS.nii'));
    MRI(m).prf_sd = load_nii(...
        fullfile(MRI_path,Monkey{m},'NonReg','BestVoxEstimate',...
        'SD.nii'));
    MRI(m).brainmask = load_nii(...
        fullfile(MRI_path,Monkey{m},'NonReg','BestVoxEstimate',...
        'brainmask.nii'));
%     MRI(m).brain = load_nii(...
%         fullfile(MRI_path,Monkey{m},'NonReg','BestVoxEstimate',...
%         [Monkey{m} '_brain.nii']));
    MRI(m).V1 = load_nii(...
        fullfile(MRI_path,Monkey{m},'NonReg','ROI','V1.nii'));
    MRI(m).V2 = load_nii(...
        fullfile(MRI_path,Monkey{m},'NonReg','ROI','V2_merged.nii'));
    MRI(m).V3 = load_nii(...
        fullfile(MRI_path,Monkey{m},'NonReg','ROI','V3_merged.nii'));
    MRI(m).V3A = load_nii(...
        fullfile(MRI_path,Monkey{m},'NonReg','ROI','V3A.nii'));
    MRI(m).V4 = load_nii(...
        fullfile(MRI_path,Monkey{m},'NonReg','ROI','V4_merged.nii'));
    MRI(m).MT = load_nii(...
        fullfile(MRI_path,Monkey{m},'NonReg','ROI','MT.nii'));
    MRI(m).MST = load_nii(...
        fullfile(MRI_path,Monkey{m},'NonReg','ROI','MST.nii'));
    MRI(m).LIP = load_nii(...
        fullfile(MRI_path,Monkey{m},'NonReg','ROI','LIP_merged.nii'));
    MRI(m).VIP = load_nii(...
        fullfile(MRI_path,Monkey{m},'NonReg','ROI','VIP.nii'));
    MRI(m).TEO = load_nii(...
        fullfile(MRI_path,Monkey{m},'NonReg','ROI','TEO.nii'));
    MRI(m).TPO = load_nii(...
        fullfile(MRI_path,Monkey{m},'NonReg','ROI','TPO.nii'));
    MRI(m).Area5 = load_nii(...
        fullfile(MRI_path,Monkey{m},'NonReg','ROI','5_merged.nii'));
    MRI(m).Area7 = load_nii(...
        fullfile(MRI_path,Monkey{m},'NonReg','ROI','7_merged.nii'));
    MRI(m).V1Electr = load_nii(...
        fullfile(MRI_path,Monkey{m},'NonReg','ROI',[Monkey{m} '_LH_V1_electrodes.nii']));
    MRI(m).V4Electr = load_nii(...
        fullfile(MRI_path,Monkey{m},'NonReg','ROI',[Monkey{m} '_LH_V4_electrodes.nii']));
end

save('pRF_estimates_MRI_inFunc','MRI')

%% 
%imagesc(MRI(1).brain.img(:,:,60)) % horizontal
%imagesc(squeeze(MRI(1).brain.img(50,:,:))) % saggital
%imagesc(squeeze(MRI(1).brain.img(:,50,:))) % coronal


