figure;
SigTypes = {'Theta','Alpha','Beta','lGamma','hGamma'};
fb=5;

s=...
    strcmp(RTE.Model,'linear_ephys_cv1') & ...
    strcmp(RTE.SigType,SigTypes{fb}) & ...
    strcmp(RTE.Monkey,'lick') & ...
    RTE.Array < 3;
scatter(R_EPHYS(1).model(1).LFP(1,fb).R2(:,1),...
    RTE.R2_1(s))