%% MRI ====================================================================
monkeys = {'eddy','danny'};

models = {...
    'linhrf_cv1_dhrf','linhrf_cv1_mhrf',...
    'linhrf_cv1_dhrf_neggain','linhrf_cv1_mhrf_neggain',...
    'doghrf_cv1_dhrf','doghrf_cv1_mhrf',...
    'csshrf_cv1_dhrf','csshrf_cv1_mhrf'};

ck_GetMRI_pRF(monkeys,models);


%% EPHYS ==================================================================
monkeys = {'lick','aston'};

models = {...
    'linear_ephys_cv1',...
    'linear_ephys_cv1_neggain',...
    'dog_ephys_cv1',...
    'css_ephys_cv1',...
    'classicRF'};

ck_GetEphys_pRF(monkeys,models);
