%% stats for linear models comparison
% do V1 only for now

%% DATA
ecc=[]; sz=[]; % eccentricity and size  
signal = []; % categorical 1=MRI, 2=MUA, 3-7=LFP bands
area=[]; % categorical 1=V1,4=V4
model=[]; % categorical 1=lin, 2=lin_ng, 3=css, 4=dog

% --- start with only the linear model ---
% MRI
ecc = [ecc; ...
    mri1(1).ECC; ...
    mua1(1).ECC; ...
    ];
sz = [ sz; ...
    mri1(1).S; ...
    mua1(1).S; ...
    ];
signal = [signal;...
    ]
area = [area; ...
    ]
    
    mri1(1).S